spring:
  application:
    name: spring-eureka-server
  security:
    user:
      name: xiaoer
      password: 123456
  profiles:
    active: peer1

server:
  port: 1110

eureka:
  instance:
    hostname: peer1 #修改前
    instance-id: ${spring.application.name}:${server.port}  #修改前
#    prefer-ip-address: true  #修改后
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://localhost:${server.port}/eureka/
#      defaultZone: http://xiaoer:123456@peer2:1210/eureka/,http://xiaoer:123456@peer3:1310/eureka/
#      defaultZone: http://xiaoer:123456@peer2:1210/eureka/,http://xiaoer:123456@peer3:1310/eureka/
#      defaultZone: http://peer2:1210/eureka/,http://peer3:1310/eureka/
      defaultZone: http://xiaoer:123456@peer1:1110/eureka/,http://xiaoer:123456@peer2:1210/eureka/,http://xiaoer:123456@peer3:1310/eureka/
  server:
      enable-self-preservation: true    #生产时,需要打开,也就是设置为true,