spring:
  application:
    name: spring-abs-order
  sleuth:
      web:
        client:
          enabled: true
      sampler:
        probability: 1.0  # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
      base-url: http://localhost:9411/   # 指定了 Zipkin 服务器的地址
server:
  port: 1120
#  tomcat:
#    max-threads: 50
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1110/eureka/


#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream


#hystrix.metrics.enabled=true
#management.endpoint.hystrix.stream.enabled=true

#hystrix.metrics.polling-interval-ms=4000




