spring:
  application:
    name: spring-abs-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.227:3306/awb?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: mysql123
server:
  port: 1112
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:1110/eureka/
      defaultZone: http://xiaoer:123456@peer1:1110/eureka/,http://xiaoer:123456@peer2:1210/eureka/,http://xiaoer:123456@peer3:1310/eureka/
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream








