#server:
#  port: 1117
#
#spring:
#  application:
#    name: configServer
#  cloud:
#    config:
#      server:


#        native:
#          search-locations: I:/
#            search-locations: /shared/
#          - classpath: /shared/
#  profiles:
#      active: native

#        git:
#          uri: https://github.com/xiaoerer/cloud-abs-config.git
#          default-label: master
#          username:
#          password:
#          search-paths: /**
#
#  rabbitmq:
#    host: localhost
#    port: 15672
#    username: xiaoer
#    password: 123456



eureka:
  client:
    service-url:
      defaultZone: http://localhost:1110/eureka/
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#      cors:
#        allowed-origins: "*"
#        allowed-methods: "*"

#Spring Cloud Config也提供本地存储配置的方式。
#我们只需要设置属性spring.profiles.active=native，Config Server会默认从应用的src/main/resource目录下检索配置文件。
#也可以通过spring.cloud.config.server.native.searchLocations=file:E:/properties/属性来指定配置文件的位置。
#虽然Spring Cloud Config提供了这样的功能，但是为了支持更好的管理内容和版本控制的功能，还是推荐使用git的方式。





spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaoerer/cloud-abs-config.git
          search-paths: /**
          username:
          password:
server:
  port: 1117











