spring:
  application:
    name: spring-auth-provider
#  sleuth:
#    web:
#      client:
#        enabled: true
#    sampler:
#      probability: 1.0  # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
#  zipkin:
#    base-url: http://localhost:9411/  # 指定了 Zipkin 服务器的地址

server:
  port: 1140
eureka:
  client:
    service-url:
      defaultZone: http://xiaoer:123456@peer1:1110/eureka/,http://xiaoer:123456@peer2:1210/eureka/,http://xiaoer:123456@peer3:1310/eureka/